---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "e-attendance-deployment"
  namespace: "default"
  labels:
    app: "e-attendance-deployment"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "e-attendance-deployment"
  template:
    metadata:
      labels:
        app: "e-attendance-deployment"
    spec:
      containers:
      - name: "backend"
        image: "gcr.io/e-attendance-hackathon/backend:latest"
        ports:
        - containerPort: 8000  # Specify the port your app listens on
---
apiVersion: "autoscaling/v2"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "e-attendance-deployment-hpa-9ayt"
  namespace: "default"
  labels:
    app: "e-attendance-deployment"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "e-attendance-deployment"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      target:
        type: "Utilization"
        averageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "e-attendance-deployment-service"
  namespace: "default"
  labels:
    app: "e-attendance-deployment"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8000  # Forward traffic from port 80 to container port 8000
  selector:
    app: "e-attendance-deployment"
  type: "LoadBalancer"
